SELECT CHR(ASCII('B'))
      ,CHR(65)
      ,SUBSTR('ASDFAFASDASD',3,5)
      ,CONCAT('A','BBB')
      ,'A'||'BBB'||'CCC'
      ,GREATEST(1,2,3)
	  
FROM DUAL;


SELECT NAME
      ,KOR
      ,ENG
      ,MAT
      ,GREATEST(KOR,ENG,MAT)
       ,LEAST(KOR,ENG,MAT) 
        ,INITCAP('ASDSDSF ASDSAD ASDASD')
        
FROM EXAM_RSLT;

SELECT INITCAP('ASDASDASD ASDSAD ASD') 
     ,LENGTH('SADASDSA')
     ,LENGTH('다아ㅏ라아')
     ,LOWER('ASDASDSAD')
     ,LPAD('#',ROWNUM,'@')
     ,LTRIM('    ABC')
     ,RTRIM('ABC   ')
FROM DUAL

CONNECT BY LEVEL <=5;

SELECT REPLACE('DFADFA','DF','##@')
       ,TRANSLATE('DFADFA','DFA','#@')
FROM DUAL;


SELECT VAR_PHONE ORG_STR
     ,TRANSLATE(VAR_PHONE,' 0123456789',' ') TST_1
       ,TRANSLATE('안9녕8하7세6요5 4H3 2입1니0다','0123456789'||VAR_PHONE,'0123456789') TST_2
FROM(SELECT '안9녕8하7세6요5 4H3 2입1니0다' AS VAR_PHONE FROM DUAL);

SELECT TRANSLATE('ALALALDDD','ALAL','BC') FROM DUAL;


-- 메타캐릭터--

SELECT  '010-2300-4567'
,REGEXP_SUBSTR('010aasd-2304-4567','[^[:digit:]]+') --not--이라는뜻
,REGEXP_SUBSTR('010aasd-2304-4567','^[a-z]+')
FROM DUAL;




