SELECT ABS(-3)
, ABS(-2)
    ,CEIL(3.25)
    ,CEIL(3.7)
    ,ROUND(2.23)
    ,ROUND(2.23,-1)
    ,ROUND(2.80)
    ,ROUND(2.267,2)
    ,FLOOR(3.7)
    ,ROUND(SYSDATE-(1/24))
    ,SYSDATE-1/24
    ,TRUNC(SYSDATE)
    ,TRUNC(17.7,-1)
FROM DUAL;


SELECT 
  ADD_MONTHS( SYSDATE,2) A
  ,TO_DATE('20211203','YYYYMMDD')+35 B
  ,CURRENT_DATE C
  ,SYSDATE D
  ,EXTRACT(YEAR FROM SYSDATE) E
  ,TO_CHAR(SYSDATE,'YYYY') F
  ,EXTRACT(MONTH FROM SYSDATE) G
  ,TO_CHAR(SYSDATE,'DD') H
  ,EXTRACT(HOUR FROM SYSTIMESTAMP) +9
  ,TO_CHAR(SYSDATE,'HH') H
   ,EXTRACT(MINUTE FROM SYSTIMESTAMP) 
  ,TO_CHAR(SYSDATE,'MI') D
  ,SYSTIMESTAMP
   ,EXTRACT(SECOND FROM SYSTIMESTAMP) 
  ,TO_CHAR(SYSDATE,'SS') D
  
FROM DUAL;

SELECT MONTHS_BETWEEN(SYSDATE, SYSDATE+100)
  ,NEXT_DAY(SYSDATE,7)
  ,TRUNC(SYSDATE)
FROM DUAL;

SELECT
ABS(-5) COL1
,ABS(5) COL2
,FLOOR(10.5) COL3
,CEIL(10.5) COL4
,POWER(2,3) COL5
,SQRT(2) COL6
,ROUND(10.4) COL7
,ROUND(10.5) COL8
,TRUNC(10.4) COL9
,TRUNC(10.5) COL10
,TRUNC(11.5,-1) COL11
,ADD_MONTHS(TO_DATE('20180101','YYYYMMDD'),3) COL12
,CURRENT_DATE COL13
,EXTRACT(YEAR FROM SYSDATE) COL14
,EXTRACT(MONTH FROM SYSDATE) COL15
,EXTRACT(DAY FROM SYSDATE) COL16
,EXTRACT(DAY FROM LAST_DAY(TO_DATE('201803','YYYYMM'))) COL17
,NEXT_DAY('20180206',2) COL18
,NEXT_DAY('20180206','월') COL19
,SYSDATE COL20
,TRUNC(SYSDATE) COL21

FROM DUAL;

SELECT SYSDATE+LEVEL-1 DT FROM DUAL CONNECT BY LEVEL <=10;

SELECT TO_CHAR(SYSDATE,'WW') FROM DUAL;


SELECT TO_DATE('20190101','YYYYMMDD')+LEVEL-1 DT
  ,TO_CHAR(TO_DATE('20190101','YYYYMMDD')+LEVEL-1,'DAY')DAY
  ,TO_CHAR(TO_DATE('20190101','YYYYMMDD')+LEVEL-1,'W')W
  ,TO_CHAR(TO_DATE('20190101','YYYYMMDD')+LEVEL-1,'WW')WW
  ,TO_CHAR(TO_DATE('20190101','YYYYMMDD')+LEVEL-1,'IW')IW
FROM DUAL CONNECT BY LEVEL <=(TO_CHAR(LAST_DAY(TO_DATE('202101','YYYYMM')),'DD'));

SELECT LAST_DAY(TO_DATE('201905','YYYYMM'))-TO_DATE('201905','YYYYMM')+1 FROM DUAL;

SELECT TO_DATE('202102','YYYYMM')+1 FROM DUAL;
SELECT LAST_DAY(TO_DATE('202102','YYYYMM'))-TO_DATE('202102','YYYYMM')+1 FROM DUAL;

SELECT TO_CHAR(LAST_DAY(TO_DATE('202102','YYYYMM')),'DD') FROM DUAL;


SELECT DT
 ,TO_CHAR(DT,'IW') IW
 ,TO_CHAR(DT,'D') D
 ,TO_CHAR(DT,'DAY') DAY
FROM

(SELECT TO_DATE('20190101','YYYYMMDD')+LEVEL-1 DT

FROM DUAL CONNECT BY LEVEL <=(TO_CHAR(LAST_DAY(TO_DATE('202101','YYYYMM')),'DD')));


SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD')
      ,TO_CHAR(TRUNC(SYSDATE),'YYYY-MM-DD')
FROM DUAL;


SELECT EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE,ROWNUM-1)) YR
 ,EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE , ROWNUM-1 )) MON
 ,EXTRACT(DAY FROM LAST_DAY(ADD_MONTHS(SYSDATE,ROWNUM-1))) MON
FROM DUAL
CONNECT BY LEVEL <= 12 *:VAAA;



SELECT 
MIN(DECODE(W_ID,1,D_ID))일
,MIN(DECODE(W_ID,2,D_ID))월
,MIN(DECODE(W_ID,3,D_ID))화
,MIN(DECODE(W_ID,4,D_ID))수
,MIN(DECODE(W_ID,5,D_ID))목
,MIN(DECODE(W_ID,6,D_ID))금
,MIN(DECODE(W_ID,7,D_ID))토
FROM
(SELECT 

TRUNC(TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1,'D') WK_ID
,TO_CHAR(TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1,'D') W_ID 
,EXTRACT(DAY FROM TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1) D_ID
FROM DUAL
CONNECT BY LEVEL <=EXTRACT(DAY FROM LAST_DAY(TO_DATE(:V_ST,'YYYYMM')))
)GROUP BY WK_ID
ORDER BY WK_ID;

SELECT TRUNC(TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1,'D') WK_ID FROM DUAL;
SELECT TO_CHAR(TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1,'D') W_ID FROM DUAL;
SELECT EXTRACT(DAY FROM TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1) D_ID FROM DUAL;

SELECT TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1 FROM DUAL;


SELECT 

TRUNC(TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1,'D') WK_ID
,TO_CHAR(TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1,'D') W_ID 
,EXTRACT(DAY FROM TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1) D_ID
FROM DUAL
CONNECT BY LEVEL <=EXTRACT(DAY FROM LAST_DAY(TO_DATE(:V_ST,'YYYYMM')));


SELECT MIN(DECODE(D_ID,1,M_ID)) MID
,
MIN(DECODE(W_ID,1,D_ID))일
,MIN(DECODE(W_ID,2,D_ID))월
,MIN(DECODE(W_ID,3,D_ID))화
,MIN(DECODE(W_ID,4,D_ID))수
,MIN(DECODE(W_ID,5,D_ID))목
,MIN(DECODE(W_ID,6,D_ID))금
,MIN(DECODE(W_ID,7,D_ID))토
FROM
(SELECT 
TO_CHAR(TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1,'YYYY-MM') M_ID
,TRUNC(TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1,'D') WK_ID
,TO_CHAR(TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1,'D') W_ID 
,EXTRACT(DAY FROM TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1) D_ID
FROM DUAL
CONNECT BY LEVEL <=

LAST_DAY(TO_DATE(:V_ET,'YYYYMM'))-TO_DATE(:V_ST,'YYYYMM')+1
)GROUP BY M_ID,WK_ID
ORDER BY M_ID, WK_ID;



SELECT EXTRACT(DAY FROM LAST_DAY(TO_DATE(:V_ST,'YYYYMM')))
FROM DUAL;

SELECT LAST_DAY(TO_DATE(:V_ET,'YYYYMM'))-TO_DATE(:V_ST,'YYYYMM')+1

FROM DUAL;


SELECT TO_CHAR(TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1,'YYYY-MM') M_ID,
TRUNC(SYSDATE+ROWNUM-1,'D') WK_ID
,TO_CHAR(SYSDATE+ROWNUM-1,'D') W_ID
,EXTRACT(DAY FROM SYSDATE+ROWNUM-1) D_ID
FROM DUAL CONNECT BY LEVEL <=LAST_DAY(TO_DATE(:V_ET,'YYYYMM'))-TO_DATE(:V_ST,'YYYYMM')+1;




	CREATE VIEW V_KJH_HW20211206_2 AS
	
	SELECT*
	FROM DUAL

		/*	SELECT MIN(DECODE(D_ID,1,M_ID)) MID
,
MIN(DECODE(W_ID,1,D_ID))일
,MIN(DECODE(W_ID,2,D_ID))월
,MIN(DECODE(W_ID,3,D_ID))화
,MIN(DECODE(W_ID,4,D_ID))수
,MIN(DECODE(W_ID,5,D_ID))목
,MIN(DECODE(W_ID,6,D_ID))금
,MIN(DECODE(W_ID,7,D_ID))토

FROM
(SELECT 
TO_CHAR(TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1,'YYYY-MM') M_ID
,TRUNC(TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1,'D') WK_ID
,TO_CHAR(TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1,'D') W_ID 
,EXTRACT(DAY FROM TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1) D_ID

FROM DUAL



CONNECT BY LEVEL <=

LAST_DAY(TO_DATE(:V_ET,'YYYYMM'))-TO_DATE(:V_ST,'YYYYMM')+1
 
)

GROUP BY M_ID,WK_ID

HAVING MIN(MOD(EXTRACT(MONTH FROM TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1),2))=:EVENODD

ORDER BY M_ID,WK_ID;*/;



SELECT 
TO_CHAR(TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1,'YYYY-MM') M_ID
,TRUNC(TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1,'D') WK_ID
,TO_CHAR(TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1,'D') W_ID 
,EXTRACT(DAY FROM TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1) D_ID

FROM 
CONNECT BY LEVEL <=

LAST_DAY(TO_DATE(:V_ET,'YYYYMM'))-TO_DATE(:V_ST,'YYYYMM')+1;



		SELECT TO_CHAR(MIN(DECODE(D_ID,1,M_ID)),'YYYY-MM') MID
,
MIN(DECODE(W_ID,1,D_ID))일
,MIN(DECODE(W_ID,2,D_ID))월
,MIN(DECODE(W_ID,3,D_ID))화
,MIN(DECODE(W_ID,4,D_ID))수
,MIN(DECODE(W_ID,5,D_ID))목
,MIN(DECODE(W_ID,6,D_ID))금
,MIN(DECODE(W_ID,7,D_ID))토

FROM
(
SELECT A.M_ID,A.WK_ID,A.W_ID,A.D_ID
FROM(
SELECT 
TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1 M_ID
,TRUNC(TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1,'D') WK_ID
,TO_CHAR(TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1,'D') W_ID 
,EXTRACT(DAY FROM TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1) D_ID


FROM DUAL

CONNECT BY LEVEL <=

LAST_DAY(TO_DATE(:V_ET,'YYYYMM'))-TO_DATE(:V_ST,'YYYYMM')+1) A, (SELECT 
ROWNUM NO

FROM DUAL

CONNECT BY LEVEL <=1) B

WHERE MOD(EXTRACT(MONTH FROM M_ID),2)=:EVENODD) C

GROUP BY WK_ID
ORDER BY WK_ID;



SELECT* FROM(
SELECT 
TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1 M_ID
,TRUNC(TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1,'D') WK_ID
,TO_CHAR(TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1,'D') W_ID 
,EXTRACT(DAY FROM TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1) D_ID

FROM DUAL

CONNECT BY LEVEL <=
LAST_DAY(TO_DATE(:V_ET,'YYYYMM'))-TO_DATE(:V_ST,'YYYYMM')+1)
WHERE MOD(EXTRACT(MONTH FROM M_ID),2) = :EVENODD;


	SELECT A.M_ID,A.WK_ID,A.W_ID,A.D_ID
FROM(
SELECT 
TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1 M_ID
,TRUNC(TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1,'D') WK_ID
,TO_CHAR(TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1,'D') W_ID 
,EXTRACT(DAY FROM TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1) D_ID


FROM DUAL

CONNECT BY LEVEL <=

LAST_DAY(TO_DATE(:V_ET,'YYYYMM'))-TO_DATE(:V_ST,'YYYYMM')+1) A, (SELECT 
ROWNUM NO

FROM DUAL

CONNECT BY LEVEL <=1) B

WHERE MOD(EXTRACT(MONTH FROM M_ID),2)=:EVENODD;




