
    SELECT AREA_CD
          ,DECODE(GROUPING(AREA_CD)||GROUPING(REGION_AREA) 
                 ,'00', MIN(CD_NM) ,'01',MIN(CD_NM)||'ÇÕ°è','ÃÑ°è') CD_NM
          ,REGION_AREA
          ,NVL(SUM(DECODE(PROD_ID,'00001',SALE_CNT)),0) COL1
          ,NVL(SUM(DECODE(PROD_ID,'00002',SALE_CNT)),0) COL2
          ,NVL(SUM(DECODE(PROD_ID,'00003',SALE_CNT)),0) COL3
          ,NVL(SUM(DECODE(PROD_ID,'00004',SALE_CNT)),0) COL4
          ,NVL(SUM(DECODE(PROD_ID,'00005',SALE_CNT)),0) COL5
          ,NVL(SUM(DECODE(PROD_ID,'00006',SALE_CNT)),0) COL6
          ,NVL(SUM(DECODE(PROD_ID,'00007',SALE_CNT)),0) COL7
          ,NVL(SUM(DECODE(PROD_ID,'00008',SALE_CNT)),0) COL8
          ,NVL(SUM(DECODE(PROD_ID,'00009',SALE_CNT)),0) COL9
          ,SUM(SALE_CNT) TOT         
          ,GROUPING(AREA_CD)||GROUPING(REGION_AREA) GR  
          ,MAX(RK) +1,MAX(RK)
    FROM (
      SELECT AREA_CD
            ,REGION_AREA
            ,PROD_ID
            ,SUM(SALE_CNT) SALE_CNT   
            ,DENSE_RANK() OVER(PARTITION BY AREA_CD,REGION_AREA ORDER BY SUM(SALE_CNT) DESC) RK
      FROM SALE_TBL
      WHERE ROWNUM <=2000000
      GROUP BY AREA_CD
              ,REGION_AREA
              ,PROD_ID
    )A, CD_TBL B
    WHERE A.AREA_CD = B.CD_ID
    GROUP BY ROLLUP(AREA_CD,REGION_AREA)  