SELECT AREA_CD
      ,CD_NM
      ,REGION_AREA
      ,COL1||' '||DECODE(COL1,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL1,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')  COL1
      ,COL2||' '||DECODE(COL2,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL2,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å') COL2
      ,COL3||' '||DECODE(COL3,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL3,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å') COL3
      ,COL4||' '||DECODE(COL4,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL4,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å') COL4
      ,COL5||' '||DECODE(COL5,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL5,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å') COL5
      ,COL6||' '||DECODE(COL6,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL6,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å') COL6
      ,COL7||' '||DECODE(COL7,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL7,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å') COL7
      ,COL8||' '||DECODE(COL8,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL8,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å') COL8
      ,COL9||' '||DECODE(COL9,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL9,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å') COL9
      ,TOT
      ,GR
FROM (
    SELECT AREA_CD
          ,DECODE(GROUPING(AREA_CD)||GROUPING(REGION_AREA) 
                 ,'00', MIN(CD_NM) ,'01',MIN(CD_NM)||'ÇÕ°è','ÃÑ°è') CD_NM
          ,REGION_AREA
         ,NVL(SUM(DECODE(PROD_ID,'00001',SALE_CNT||RANKNUM)),0) COL1
,NVL(SUM(DECODE(PROD_ID,'00002',SALE_CNT||RANKNUM)),0) COL2
,NVL(SUM(DECODE(PROD_ID,'00003',SALE_CNT||RANKNUM)),0) COL3
,NVL(SUM(DECODE(PROD_ID,'00004',SALE_CNT||RANKNUM)),0) COL4
,NVL(SUM(DECODE(PROD_ID,'00005',SALE_CNT||RANKNUM)),0) COL5
,NVL(SUM(DECODE(PROD_ID,'00006',SALE_CNT||RANKNUM)),0) COL6
,NVL(SUM(DECODE(PROD_ID,'00007',SALE_CNT||RANKNUM)),0) COL7
,NVL(SUM(DECODE(PROD_ID,'00008',SALE_CNT||RANKNUM)),0) COL8
,NVL(SUM(DECODE(PROD_ID,'00009',SALE_CNT||RANKNUM)),0) COL9
,RANK() OVER(PARTITION BY REGION_AREA,AREA_CD ORDER BY SALE_CNT DESC) RANKNUM

          ,SUM(SALE_CNT) TOT         
          ,GROUPING(AREA_CD)||GROUPING(REGION_AREA) GR             
    FROM (
    
       SELECT
             AREA_CD
            ,REGION_AREA
            ,PROD_ID
            ,SALE_CNT 
              
    FROM(
      SELECT AREA_CD
            ,REGION_AREA
            ,PROD_ID
            ,SUM(SALE_CNT) SALE_CNT   
      FROM SALE_TBL
      WHERE ROWNUM <=6000000
      GROUP BY AREA_CD
              ,REGION_AREA
              ,PROD_ID
              
    )GROUP BY AREA_CD
              ,REGION_AREA
              ,PROD_ID
              ,SALE_CNT )A, CD_TBL B
    WHERE A.AREA_CD = B.CD_ID
    GROUP BY ROLLUP(AREA_CD,REGION_AREA)
);