select* from employees;

select*from PRODUCTS;
SELECT*FROM ORDER_ITEMS;

select*from ORDERS WHERE CUSTOMER_ID=1;
SELECT*FROM CUSTOMERS;

SELECT * FROM  CUSTOMERS C,ORDERS O WHERE  C.CUSTOMER_ID = O.CUSTOMER_ID; 


SELECT* FROM(
SELECT OTT.ORDER_ID,OTT.CUSTOMER_ID,P.* FROM(
SELECT O.ORDER_ID,O.CUSTOMER_ID,O.STATUS,O.SALESMAN_ID,O.ORDER_DATE,OT.ITEM_ID,OT.PRODUCT_ID,OT.QUANTITY,OT.UNIT_PRICE FROM ORDERS O ,ORDER_ITEMS OT WHERE O.ORDER_ID = OT.ORDER_ID)
OTT, PRODUCTS P WHERE OTT.PRODUCT_ID= P.PRODUCT_ID) A, CUSTOMERS C WHERE C.CUSTOMER_ID=A.CUSTOMER_ID ORDER BY A.CUSTOMER_ID;


SELECT COUNT(*) FROM ORDER_ITEMS;

SELECT* FROM ORDER_ITEMS OT,ORDERS O, PRODUCTS P, CUSTOMERS C WHERE OT.ORDER_ID=O.ORDER_ID AND OT.PRODUCT_ID=P.PRODUCT_ID AND O.CUSTOMER_ID=C.CUSTOMER_ID
AND C.CUSTOMER_ID=1
ORDER BY C.CUSTOMER_ID;

SELECT *FROM ORDERS O ,ORDER_ITEMS OT WHERE O.ORDER_ID = OT.ORDER_ID;