
SELECT
NO, MM
,DECODE(MM2,NULL,MM3,MM2) MM2
,NM
FROM(
SELECT
ROWNUM
,NO
,MM
,MM2
,LEAD(MM2) OVER(PARTITION BY NM ORDER BY NM) MM3
,NM

FROM(
SELECT 
NO
,ST_DT
,ET_DT
,DECODE(SIGN(ST_DT-NVL(LAG(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0)),0,NULL,1,ST_DT,-1,ST_DT) MM
,DECODE(SIGN(ET_DT-NVL(LEAD(ST_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0)),0,NULL,1,ET_DT,-1,ET_DT) MM2
,NM
FROM ORG_TBL
ORDER BY NM,ET_DT)
WHERE MM||MM2 IS NOT NULL)
WHERE MM IS NOT NULL;






select MIN(no)
,MIN(ST_DT)
,MAX(ET_DT)
,NM
FROM ORG_TBL
GROUP BY NM;



SELECT
MIN(NO)
,DECODE(SAME,1,ST_DT-NET,0,ST_DT) ST_DT
,MAX(ET_DT)
,MAX(NM)
FROM(
SELECT 
NO,ST_DT,ET_DT,NM
,LAG(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT) NET
,DECODE(ST_DT,LAG(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT),1,0) SAME
FROM ORG_TBL)
GROUP BY DECODE(SAME,1,ST_DT-NET,0,ST_DT);


SELECT 

NO
,ST_DT-NVL(LAG(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0) ST_DT
,ET_DT,NM

,NVL(LAG(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0) NET
,NVL(LAG(ST_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0) NET2
,DECODE(ST_DT,LAG(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT),1,0) SAME
FROM ORG_TBL;



SELECT

NO
,ST_DT
,ET_DT
,NM
,LEAD(ST_DT) OVER(PARTITION BY NM ORDER BY ET_DT) UET
,NET
,NET2

FROM(
SELECT 

NO
,ST_DT-NVL(LAG(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0) ST_DT
,ET_DT,NM

,NVL(LAG(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0) NET
,NVL(LAG(ST_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0) NET2
,DECODE(ST_DT,LAG(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT),1,0) SAME

FROM ORG_TBL
WHERE NM='±Ë¿ØΩ≈'
ORDER BY ET_DT);




SELECT

NO
,DECODE(SIGN(ST_DT-NVL(LEAD(ST_DT) OVER(PARTITION BY NM ORDER BY ET_DT),0)),1,ST_DT+NET,-1,ET_DT,0)
,ET_DT
,NM
,NVL(LEAD(ST_DT) OVER(PARTITION BY NM ORDER BY ET_DT),0) UET
,NET
,NET2

FROM(
SELECT 

NO
,ST_DT-NVL(LAG(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0) ST_DT
,ET_DT,NM

,NVL(LAG(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0) NET
,NVL(LAG(ST_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0) NET2
,DECODE(ST_DT,LAG(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT),1,0) SAME

FROM ORG_TBL

ORDER BY NM,ET_DT);




SELECT*FROM
ORG_TBL
ORDER BY NM,ST_DT;




SELECT
NO
,DECODE(SIGN(ST_DT-NET),0,NST,1,ST_DT,-1,NET)
,DECODE(SIGN(ET_DT-UST),0,UET,1,ET_DT,-1,UST)
,NM

FROM(

SELECT 

NO
,ST_DT
,ET_DT
,NM
,NVL(LEAD(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0) UET
,NVL(LEAD(ST_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0)UST
,NVL(LAG(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0) NET
,NVL(LAG(ST_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0) NST
,DECODE(ST_DT,LAG(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT),1,0) SAME

FROM ORG_TBL

ORDER BY NM,ET_DT);




SELECT 
NO
,ST_DT
,ET_DT
,DECODE(SIGN(ST_DT-NVL(LAG(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0)),0,NULL,1,ST_DT,-1,ST_DT) MM
,DECODE(SIGN(ET_DT-NVL(LEAD(ST_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0)),0,NULL,1,ET_DT,-1,ET_DT) MM2
,NM
,NVL(LEAD(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0) UET
,NVL(LEAD(ST_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0)UST
,NVL(LAG(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0) NET
,NVL(LAG(ST_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0) NST



FROM ORG_TBL
ORDER BY NM,ET_DT;




SELECT 

NO
,ST_DT
,ET_DT
,NM
,NVL(LEAD(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0) UET
,NVL(LEAD(ST_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0)UST
,NVL(LAG(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0) NET
,NVL(LAG(ST_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0) NST
,DECODE(ST_DT,LAG(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT),1,0) SAME

FROM ORG_TBL

ORDER BY NM,ET_DT;





SELECT *FROM ORG_TBL
ORDER BY NM,ST_DT;



SELECT
NO, MM
,DECODE(MM2,NULL,MM3,MM2) MM2
,NM
FROM(
SELECT
ROWNUM
,NO
,MM
,MM2
,LEAD(MM2) OVER(PARTITION BY NM ORDER BY NM) MM3
,NM

FROM(
SELECT 
NO
,ST_DT
,ET_DT
,DECODE(SIGN(ST_DT-NVL(LAG(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0)),0,NULL,1,ST_DT,-1,ST_DT) MM
,DECODE(SIGN(ET_DT-NVL(LEAD(ST_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0)),0,NULL,1,ET_DT,-1,ET_DT) MM2
,NM
FROM ORG_TBL
ORDER BY NM,ET_DT)
WHERE MM||MM2 IS NOT NULL)
WHERE MM IS NOT NULL;


SELECT
ROWNUM
,NO
,MM
,MM2
,LEAD(MM2) OVER(PARTITION BY NM ORDER BY NM) MM3
,NM

FROM(
SELECT 
NO
,ST_DT
,ET_DT
,DECODE(SIGN(ST_DT-NVL(LAG(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0)),0,NULL,1,ST_DT,-1,ST_DT) MM
,DECODE(SIGN(ET_DT-NVL(LEAD(ST_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0)),0,NULL,1,ET_DT,-1,ET_DT) MM2
,NM
,NVL(LEAD(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0) UET
,NVL(LEAD(ST_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0)UST
,NVL(LAG(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0) NET
,NVL(LAG(ST_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0) NST



FROM ORG_TBL
ORDER BY NM,ET_DT)
WHERE MM||MM2 IS NOT NULL;

SELECT* FROM ORG_TBL 
ORDER BY NM,ST_DT;


	SELECT A.MST_ID       MST_ID    
		      ,A.MST_NAME     MST_NAME
		      ,A.DEBUT_DATE   DEBUT_DATE
		      ,B.ALBUM_ID     ALBUM_ID  
		      ,B.ALBUM_SEQ    ALBUM_SEQ 
		      ,B.ALBUM_TITLE  ALBUM_TITLE
		      ,B.OPEN_DATE    OPEN_DATE
		      ,C.SONG_NAME    SONG_NAME
		      ,C.PLAY_TIME    PLAY_TIME
		FROM ARTIST A,ALBUM B,SONG C
		WHERE A.MST_ID = B.MST_ID
		  AND B.ALBUM_ID = C.ALBUM_ID
		  AND B.ALBUM_ID = 'BS1';

