
 SELECT AREA_CD
      ,CD_NM
      ,REGION_AREA
      ,DECODE(LENGTH(CD_NM),2,SUBSTR(TO_CHAR(COL1),1,LENGTH(TO_CHAR(COL1))-1),COL1)||' '||DECODE(COL1,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL1,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||DECODE(SUBSTR(TO_CHAR(COL1),-1),0,10,SUBSTR(TO_CHAR(COL1),-1))  COL1
      ,SUBSTR(TO_CHAR(COL2),1,LENGTH(TO_CHAR(COL2))-1)||' '||DECODE(COL2,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL2,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||DECODE(SUBSTR(TO_CHAR(COL2),-1),0,10,SUBSTR(TO_CHAR(COL2),-1))  COL2
      ,SUBSTR(TO_CHAR(COL3),1,LENGTH(TO_CHAR(COL3))-1)||' '||DECODE(COL3,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL3,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||DECODE(SUBSTR(TO_CHAR(COL3),-1),0,10,SUBSTR(TO_CHAR(COL3),-1))  COL3
      ,SUBSTR(TO_CHAR(COL4),1,LENGTH(TO_CHAR(COL4))-1)||' '||DECODE(COL4,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL4,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||DECODE(SUBSTR(TO_CHAR(COL4),-1),0,10,SUBSTR(TO_CHAR(COL4),-1)) COL4
      ,SUBSTR(TO_CHAR(COL5),1,LENGTH(TO_CHAR(COL5))-1)||' '||DECODE(COL5,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL5,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||DECODE(SUBSTR(TO_CHAR(COL5),-1),0,10,SUBSTR(TO_CHAR(COL5),-1))  COL5
      ,SUBSTR(TO_CHAR(COL6),1,LENGTH(TO_CHAR(COL6))-1)||' '||DECODE(COL6,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL6,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||DECODE(SUBSTR(TO_CHAR(COL6),-1),0,10,SUBSTR(TO_CHAR(COL6),-1))  COL6
      ,SUBSTR(TO_CHAR(COL7),1,LENGTH(TO_CHAR(COL7))-1)||' '||DECODE(COL7,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL7,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||DECODE(SUBSTR(TO_CHAR(COL7),-1),0,10,SUBSTR(TO_CHAR(COL7),-1))  COL7
      ,SUBSTR(TO_CHAR(COL8),1,LENGTH(TO_CHAR(COL8))-1)||' '||DECODE(COL8,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL8,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||DECODE(SUBSTR(TO_CHAR(COL8),-1),0,10,SUBSTR(TO_CHAR(COL8),-1))  COL8
      ,SUBSTR(TO_CHAR(COL9),1,LENGTH(TO_CHAR(COL9))-1)||' '||DECODE(COL9,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL9,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||DECODE(SUBSTR(TO_CHAR(COL9),-1),0,10,SUBSTR(TO_CHAR(COL9),-1))  COL9
      ,TOT
      ,GR
FROM (
    SELECT AREA_CD
          ,DECODE(GROUPING(AREA_CD)||GROUPING(REGION_AREA) 
                 ,'00', MIN(CD_NM) ,'01',MIN(CD_NM)||'ÇÕ°è','ÃÑ°è') CD_NM
          ,REGION_AREA
         ,NVL(SUM(DECODE(PROD_ID,'00001',SALE_CNT||RANKNUM)),0) COL1
,NVL(SUM(DECODE(PROD_ID,'00002',SALE_CNT||RANKNUM)),0) COL2
,NVL(SUM(DECODE(PROD_ID,'00003',SALE_CNT||RANKNUM)),0) COL3
,NVL(SUM(DECODE(PROD_ID,'00004',SALE_CNT||RANKNUM)),0) COL4
,NVL(SUM(DECODE(PROD_ID,'00005',SALE_CNT||RANKNUM)),0) COL5
,NVL(SUM(DECODE(PROD_ID,'00006',SALE_CNT||RANKNUM)),0) COL6
,NVL(SUM(DECODE(PROD_ID,'00007',SALE_CNT||RANKNUM)),0) COL7
,NVL(SUM(DECODE(PROD_ID,'00008',SALE_CNT||RANKNUM)),0) COL8
,NVL(SUM(DECODE(PROD_ID,'00009',SALE_CNT||RANKNUM)),0) COL9


          ,SUM(SALE_CNT) TOT         
          ,GROUPING(AREA_CD)||GROUPING(REGION_AREA) GR             
    FROM (
    
       SELECT
             AREA_CD
            ,REGION_AREA
            ,PROD_ID
            ,SALE_CNT 
            ,RANK() OVER(PARTITION BY REGION_AREA,AREA_CD ORDER BY SALE_CNT DESC) RANKNUM
    FROM(
      SELECT AREA_CD
            ,REGION_AREA
            ,PROD_ID
            ,SUM(SALE_CNT) SALE_CNT   
      FROM SALE_TBL
      WHERE ROWNUM <=6000000
      GROUP BY AREA_CD
              ,REGION_AREA
              ,PROD_ID
              
    )GROUP BY AREA_CD
              ,REGION_AREA
              ,PROD_ID
              ,SALE_CNT )A, CD_TBL B
    WHERE A.AREA_CD = B.CD_ID
    GROUP BY ROLLUP(AREA_CD,REGION_AREA)
);



SELECT
      AREA_CD
      ,CD_NM
      ,REGION_AREA
      ,DECODE(GR,01,SUBSTR(TO_CHAR(COL1),1,LENGTH(COL1)-1),COL1) COL1
      ,DECODE(GR,01,SUBSTR(TO_CHAR(COL2),1,LENGTH(COL2)-1),COL2) COL2
      ,DECODE(GR,01,SUBSTR(TO_CHAR(COL3),1,LENGTH(COL3)-1),COL3)COL3
      ,DECODE(GR,01,SUBSTR(TO_CHAR(COL4),1,LENGTH(COL4)-1),COL4) COL4
      ,DECODE(GR,01,SUBSTR(TO_CHAR(COL5),1,LENGTH(COL5)-1),COL5) COL5
      ,DECODE(GR,01,SUBSTR(TO_CHAR(COL6),1,LENGTH(COL6)-1),COL6) COL6
      ,DECODE(GR,01,SUBSTR(TO_CHAR(COL7),1,LENGTH(COL7)-1),COL7) COL7
      ,DECODE(GR,01,SUBSTR(TO_CHAR(COL8),1,LENGTH(COL8)-1),COL8) COL8
      ,DECODE(GR,01,SUBSTR(TO_CHAR(COL9),1,LENGTH(COL9)-1),COL9) COL9
      ,TOT
      ,GR


FROM(
SELECT AREA_CD
      ,CD_NM
      ,REGION_AREA
      ,MAX(COL1||' '||DECODE(COL1,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL1,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||RANKNUM) COL1
      ,MAX(COL2||' '||DECODE(COL2,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL2,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||RANKNUM) COL2
      ,MAX(COL3||' '||DECODE(COL3,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL3,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||RANKNUM) COL3
      ,MAX(COL4||' '||DECODE(COL4,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL4,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||RANKNUM) COL4
      ,MAX(COL5||' '||DECODE(COL5,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL5,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||RANKNUM) COL5
      ,MAX(COL6||' '||DECODE(COL6,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL6,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||RANKNUM) COL6
      ,MAX(COL7||' '||DECODE(COL7,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL7,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||RANKNUM) COL7
      ,MAX(COL8||' '||DECODE(COL8,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL8,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||RANKNUM) COL8
      ,MAX(COL9||' '||DECODE(COL9,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL9,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||RANKNUM) COL9
      ,MAX(TOT) TOT
      ,MAX(GR) GR
   
FROM (
    SELECT AREA_CD
          ,DECODE(GROUPING(AREA_CD)||GROUPING(REGION_AREA) 
                 ,'00', MIN(CD_NM) ,'01',MIN(CD_NM)||'ÇÕ°è','ÃÑ°è') CD_NM
          ,REGION_AREA
         ,NVL(SUM(DECODE(PROD_ID,'00001',SALE_CNT)),0) COL1
,NVL(SUM(DECODE(PROD_ID,'00002',SALE_CNT)),0) COL2
,NVL(SUM(DECODE(PROD_ID,'00003',SALE_CNT)),0) COL3
,NVL(SUM(DECODE(PROD_ID,'00004',SALE_CNT)),0) COL4
,NVL(SUM(DECODE(PROD_ID,'00005',SALE_CNT)),0) COL5
,NVL(SUM(DECODE(PROD_ID,'00006',SALE_CNT)),0) COL6
,NVL(SUM(DECODE(PROD_ID,'00007',SALE_CNT)),0) COL7
,NVL(SUM(DECODE(PROD_ID,'00008',SALE_CNT)),0) COL8
,NVL(SUM(DECODE(PROD_ID,'00009',SALE_CNT)),0) COL9
,RANKNUM

          ,SUM(SALE_CNT) TOT         
          ,GROUPING(AREA_CD)||GROUPING(REGION_AREA)||RANKNUM GR             
    FROM (
    
       SELECT
             AREA_CD
            ,REGION_AREA
            ,PROD_ID
            ,SALE_CNT 
            ,RANK() OVER(PARTITION BY REGION_AREA,AREA_CD ORDER BY SALE_CNT DESC) RANKNUM 
    FROM(
      SELECT AREA_CD
            ,REGION_AREA
            ,PROD_ID
            ,SUM(SALE_CNT) SALE_CNT   
      FROM SALE_TBL
      WHERE ROWNUM <=6000000
      GROUP BY AREA_CD
              ,REGION_AREA
              ,PROD_ID
              
    )GROUP BY AREA_CD
              ,REGION_AREA
              ,PROD_ID
              ,SALE_CNT )A, CD_TBL B
    WHERE A.AREA_CD = B.CD_ID
    GROUP BY ROLLUP(AREA_CD,REGION_AREA,RANKNUM)
) GROUP BY AREA_CD
      ,CD_NM
      ,REGION_AREA
      ORDER BY AREA_CD);
    




 SELECT AREA_CD
          ,DECODE(GROUPING(AREA_CD)||GROUPING(REGION_AREA) 
                 ,'00', MIN(CD_NM) ,'01',MIN(CD_NM)||'ÇÕ°è','ÃÑ°è') CD_NM
          ,REGION_AREA
         ,NVL(SUM(DECODE(PROD_ID,'00001',SALE_CNT)),0) COL1
,NVL(SUM(DECODE(PROD_ID,'00002',SALE_CNT)),0) COL2
,NVL(SUM(DECODE(PROD_ID,'00003',SALE_CNT)),0) COL3
,NVL(SUM(DECODE(PROD_ID,'00004',SALE_CNT)),0) COL4
,NVL(SUM(DECODE(PROD_ID,'00005',SALE_CNT)),0) COL5
,NVL(SUM(DECODE(PROD_ID,'00006',SALE_CNT)),0) COL6
,NVL(SUM(DECODE(PROD_ID,'00007',SALE_CNT)),0) COL7
,NVL(SUM(DECODE(PROD_ID,'00008',SALE_CNT)),0) COL8
,NVL(SUM(DECODE(PROD_ID,'00009',SALE_CNT)),0) COL9
,RANKNUM

          ,SUM(SALE_CNT) TOT         
          ,GROUPING(AREA_CD)||GROUPING(REGION_AREA)||RANKNUM GR             
    FROM (
    
       SELECT
             AREA_CD
            ,REGION_AREA
            ,PROD_ID
            ,SALE_CNT 
            ,RANK() OVER(PARTITION BY REGION_AREA,AREA_CD ORDER BY SALE_CNT DESC) RANKNUM 
    FROM(
      SELECT AREA_CD
            ,REGION_AREA
            ,PROD_ID
            ,SUM(SALE_CNT) SALE_CNT   
      FROM SALE_TBL
      WHERE ROWNUM <=6000000
      GROUP BY AREA_CD
              ,REGION_AREA
              ,PROD_ID
              
    )GROUP BY AREA_CD
              ,REGION_AREA
              ,PROD_ID
              ,SALE_CNT )A, CD_TBL B
    WHERE A.AREA_CD = B.CD_ID
    GROUP BY ROLLUP(AREA_CD,REGION_AREA,RANKNUM);
    
    
    
    
    
    
    
    
    
    
    
    
    

SELECT
      AREA_CD
      ,CD_NM
      ,REGION_AREA
      ,DECODE(GR,01,SUBSTR(TO_CHAR(COL1),1,LENGTH(COL1)-1),COL1) COL1
      ,DECODE(GR,01,SUBSTR(TO_CHAR(COL2),1,LENGTH(COL2)-1),COL2) COL2
      ,DECODE(GR,01,SUBSTR(TO_CHAR(COL3),1,LENGTH(COL3)-1),COL3)COL3
      ,DECODE(GR,01,SUBSTR(TO_CHAR(COL4),1,LENGTH(COL4)-1),COL4) COL4
      ,DECODE(GR,01,SUBSTR(TO_CHAR(COL5),1,LENGTH(COL5)-1),COL5) COL5
      ,DECODE(GR,01,SUBSTR(TO_CHAR(COL6),1,LENGTH(COL6)-1),COL6) COL6
      ,DECODE(GR,01,SUBSTR(TO_CHAR(COL7),1,LENGTH(COL7)-1),COL7) COL7
      ,DECODE(GR,01,SUBSTR(TO_CHAR(COL8),1,LENGTH(COL8)-1),COL8) COL8
      ,DECODE(GR,01,SUBSTR(TO_CHAR(COL9),1,LENGTH(COL9)-1),COL9) COL9
      ,TOT
      ,GR


FROM(
SELECT AREA_CD
      ,CD_NM
      ,REGION_AREA
      ,MAX(COL1||' '||DECODE(COL1,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL1,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||RANKNUM) COL1
      ,MAX(COL2||' '||DECODE(COL2,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL2,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||RANKNUM) COL2
      ,MAX(COL3||' '||DECODE(COL3,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL3,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||RANKNUM) COL3
      ,MAX(COL4||' '||DECODE(COL4,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL4,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||RANKNUM) COL4
      ,MAX(COL5||' '||DECODE(COL5,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL5,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||RANKNUM) COL5
      ,MAX(COL6||' '||DECODE(COL6,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL6,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||RANKNUM) COL6
      ,MAX(COL7||' '||DECODE(COL7,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL7,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||RANKNUM) COL7
      ,MAX(COL8||' '||DECODE(COL8,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL8,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||RANKNUM) COL8
      ,MAX(COL9||' '||DECODE(COL9,GREATEST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡ã')||DECODE(COL9,LEAST(COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9),'¡å')||'*'||RANKNUM) COL9
      ,MAX(TOT) TOT
      ,MAX(GR) GR
   
FROM (
    SELECT AREA_CD
          ,DECODE(GROUPING(AREA_CD)||GROUPING(REGION_AREA) 
                 ,'00', MIN(CD_NM) ,'01',MIN(CD_NM)||'ÇÕ°è','ÃÑ°è') CD_NM
          ,REGION_AREA
         ,NVL(SUM(DECODE(PROD_ID,'00001',SALE_CNT)),0) COL1
,NVL(SUM(DECODE(PROD_ID,'00002',SALE_CNT)),0) COL2
,NVL(SUM(DECODE(PROD_ID,'00003',SALE_CNT)),0) COL3
,NVL(SUM(DECODE(PROD_ID,'00004',SALE_CNT)),0) COL4
,NVL(SUM(DECODE(PROD_ID,'00005',SALE_CNT)),0) COL5
,NVL(SUM(DECODE(PROD_ID,'00006',SALE_CNT)),0) COL6
,NVL(SUM(DECODE(PROD_ID,'00007',SALE_CNT)),0) COL7
,NVL(SUM(DECODE(PROD_ID,'00008',SALE_CNT)),0) COL8
,NVL(SUM(DECODE(PROD_ID,'00009',SALE_CNT)),0) COL9
,RANKNUM

          ,SUM(SALE_CNT) TOT         
          ,GROUPING(AREA_CD)||GROUPING(REGION_AREA)||RANKNUM GR             
    FROM (
    
       SELECT
             AREA_CD
            ,REGION_AREA
            ,PROD_ID
            ,SALE_CNT 
            ,RANK() OVER(PARTITION BY REGION_AREA,AREA_CD ORDER BY SALE_CNT DESC) RANKNUM 
    FROM(
      SELECT AREA_CD
            ,REGION_AREA
            ,PROD_ID
            ,SUM(SALE_CNT) SALE_CNT   
      FROM SALE_TBL
      WHERE ROWNUM <=6000000
      GROUP BY AREA_CD
              ,REGION_AREA
              ,PROD_ID
              
    )GROUP BY AREA_CD
              ,REGION_AREA
              ,PROD_ID
              ,SALE_CNT )A, CD_TBL B
    WHERE A.AREA_CD = B.CD_ID
    GROUP BY ROLLUP(AREA_CD,REGION_AREA,RANKNUM)
) GROUP BY AREA_CD
      ,CD_NM
      ,REGION_AREA
      ORDER BY AREA_CD);
      
      
      
      
      
      SELECT AREA_CD
          ,DECODE(GROUPING(AREA_CD)||GROUPING(REGION_AREA) 
                 ,'00', MIN(CD_NM) ,'01',MIN(CD_NM)||'ÇÕ°è','ÃÑ°è') CD_NM
          ,REGION_AREA
         ,NVL(SUM(DECODE(PROD_ID,'00001',SALE_CNT)),0) COL1
,NVL(SUM(DECODE(PROD_ID,'00002',SALE_CNT)),0) COL2
,NVL(SUM(DECODE(PROD_ID,'00003',SALE_CNT)),0) COL3
,NVL(SUM(DECODE(PROD_ID,'00004',SALE_CNT)),0) COL4
,NVL(SUM(DECODE(PROD_ID,'00005',SALE_CNT)),0) COL5
,NVL(SUM(DECODE(PROD_ID,'00006',SALE_CNT)),0) COL6
,NVL(SUM(DECODE(PROD_ID,'00007',SALE_CNT)),0) COL7
,NVL(SUM(DECODE(PROD_ID,'00008',SALE_CNT)),0) COL8
,NVL(SUM(DECODE(PROD_ID,'00009',SALE_CNT)),0) COL9
,RANKNUM

          ,SUM(SALE_CNT) TOT         
          ,GROUPING(AREA_CD)||GROUPING(REGION_AREA)||RANKNUM GR             
    FROM (
    
       SELECT
             AREA_CD
            ,REGION_AREA
            ,PROD_ID
            ,SALE_CNT 
            ,RANK() OVER(PARTITION BY REGION_AREA,AREA_CD ORDER BY SALE_CNT DESC) RANKNUM 
    FROM(
      SELECT AREA_CD
            ,REGION_AREA
            ,PROD_ID
            ,SUM(SALE_CNT) SALE_CNT   
      FROM SALE_TBL
      WHERE ROWNUM <=6000000
      GROUP BY AREA_CD
              ,REGION_AREA
              ,PROD_ID
              
    )GROUP BY AREA_CD
              ,REGION_AREA
              ,PROD_ID
              ,SALE_CNT )A, CD_TBL B
    WHERE A.AREA_CD = B.CD_ID
    GROUP BY ROLLUP(AREA_CD,REGION_AREA,RANKNUM);
    
    
    
    
 
