/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2021-11-14 02:35:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/DEV/STS_Study/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PartyCode/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1630463239938L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 부트스트랩 css 사용 -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/bootstrap.css\">\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\">\r\n");
      out.write("    </script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bootstrap.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jqueryIMPORTANT.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main2.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main2.css\">\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Nanum+Pen+Script&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"bobody\">\r\n");
      out.write("<img style=\"position:absolute; left:700px; width:1200px; height:1330px; top:0px; border:0;\"  src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/pngegg.png\">\r\n");
      out.write("<div style=\"position:absolute; left:1000px; top:500px;font-family:'Nanum Pen Script', cursive; font-size:120px;\">\r\n");
      out.write("PARTYCODE</div>\r\n");
      out.write("    <div id=\"menu\" class=\"mme\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"head\" style=\"position:relative; font-size:80px; font-family:'Nanum Pen Script', cursive;\" >SNS\r\n");
      out.write("        <img style=\"position:absolute; width:300px; height:400px; left:-140px; top:-120px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/hheart.png\"></div>\r\n");
      out.write("            <div class=\"menu-inner\">\r\n");
      out.write("                \r\n");
      out.write("                    <div class=\"container-3\">\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                            <div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\" >\r\n");
      out.write("                                <!-- Indicators -->\r\n");
      out.write("                                <ol class=\"carousel-indicators\">\r\n");
      out.write("                                  <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("                                  <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("                                  <li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("                                </ol>\r\n");
      out.write("                            \r\n");
      out.write("                                <!-- Wrapper for slides -->\r\n");
      out.write("                                <div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("                                  <div class=\"item active\">\r\n");
      out.write("                                    <img id=\"mmig\" src=\"\" alt=\"New York\" width=\"100%\" height=\"100%\">\r\n");
      out.write("                                    <div class=\"carousel-caption\">\r\n");
      out.write("                                      <h3>New York</h3>\r\n");
      out.write("                                      <p>The atmosphere in New York is lorem ipsum.</p>\r\n");
      out.write("                                    </div>      \r\n");
      out.write("                                  </div>\r\n");
      out.write("                            \r\n");
      out.write("                                  <div class=\"item\">\r\n");
      out.write("                                    <img id=\"mmig\" src=\"\" alt=\"Chicago\" width=\"600\" height=\"800\">\r\n");
      out.write("                                    <div class=\"carousel-caption\">\r\n");
      out.write("                                      <h3>Chicago</h3>\r\n");
      out.write("                                      <p>Thank you, Chicago - A night we won't forget.</p>\r\n");
      out.write("                                    </div>      \r\n");
      out.write("                                  </div>\r\n");
      out.write("                                \r\n");
      out.write("                                  <div class=\"item\">\r\n");
      out.write("                                    <img id=\"mmig\" src=\"\" alt=\"Los Angeles\" width=\"600\" height=\"800\">\r\n");
      out.write("                                    <div class=\"carousel-caption\">\r\n");
      out.write("                                      <h3>LA</h3>\r\n");
      out.write("                                      <p>Even though the traffic was a mess, we had the best time playing at Venice Beach!</p>\r\n");
      out.write("                                    </div>      \r\n");
      out.write("                                  </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            \r\n");
      out.write("                                <!-- Left and right controls -->\r\n");
      out.write("                                <a class=\"left carousel-control\" href=\"#myCarousel\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("                                  <span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                  <span class=\"sr-only\">Previous</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a class=\"right carousel-control\" href=\"users/profile?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${users.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("                                  <span class=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                  <span class=\"sr-only\">Next</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                        \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- <div class=\"u1\">\r\n");
      out.write("                                <img class=\"ch1\" src=\"img/테스트이미지.jpg\">\r\n");
      out.write("                                <a href=\"#\"><p class=\"txt1\" >Update</p></a>    \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"u2\">\r\n");
      out.write("                                <img class=\"ch2\" src=\"img/테스트이미지.jpg\">\r\n");
      out.write("                                <a href=\"#\"><p class=\"txt2\" >Test</p></a> \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"u3\">\r\n");
      out.write("                                <img class=\"ch3\" src=\"img/테스트이미지.jpg\">\r\n");
      out.write("                                <a href=\"#\"><p class=\"txt3\" >Test</p></a> \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"u4\">\r\n");
      out.write("                                <img class=\"ch4\" src=\"img/테스트이미지.jpg\">\r\n");
      out.write("                                <a href=\"#\"><p class=\"txt4\" >Test</p></a> \r\n");
      out.write("                            </div> -->\r\n");
      out.write("                        \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("            </div>   \r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bootstrap.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"menu_r\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"menu-inner_r\">\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <div class=\"head_r\" style=\"font-family:'Nanum Pen Script', cursive;\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/partyboard/party_board\">Party</a></div>\r\n");
      out.write("          \r\n");
      out.write("                \r\n");
      out.write("                <div class=\"container_r\">\r\n");
      out.write("                    \r\n");
      out.write("                    <div id=\"MyCarousel\" class=\"carousel slide casl\" data-ride=\"carousel\" >\r\n");
      out.write("                        <!-- Indicators -->\r\n");
      out.write("                        <ol class=\"carousel-indicators\">\r\n");
      out.write("                          <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("                          <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("                          <li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                    \r\n");
      out.write("                        <!-- Wrapper for slides -->\r\n");
      out.write("                        <div class=\"carousel-inner\" role=\"listbox\"> \r\n");
      out.write("                          <div class=\"item active\">\r\n");
      out.write("                            <img id=\"mig\" src=\"\" alt=\"New York\" width=\"100%\" height=\"100%\" >\r\n");
      out.write("                            <div class=\"carousel-caption\">\r\n");
      out.write("                              <h3>New York</h3>\r\n");
      out.write("                              <p>The atmosphere in New York is lorem ipsum.</p>\r\n");
      out.write("                            </div>      \r\n");
      out.write("                          </div>\r\n");
      out.write("                    \r\n");
      out.write("                          <div class=\"item\">\r\n");
      out.write("                            <img id=\"mig\" src=\"\" alt=\"Chicago\" width=\"600\" height=\"800\">\r\n");
      out.write("                            <div class=\"carousel-caption\">\r\n");
      out.write("                              <h3>Chicago</h3>\r\n");
      out.write("                              <p>Thank you, Chicago - A night we won't forget.</p>\r\n");
      out.write("                            </div>      \r\n");
      out.write("                          </div>\r\n");
      out.write("                        \r\n");
      out.write("                          <div class=\"item\">\r\n");
      out.write("                            <img id=\"mig\" src=\"\" alt=\"Los Angeles\" width=\"600\" height=\"800\">\r\n");
      out.write("                            <div class=\"carousel-caption\">\r\n");
      out.write("                              <h3>LA</h3>\r\n");
      out.write("                              <p>Even though the traffic was a mess, we had the best time playing at Venice Beach!</p>\r\n");
      out.write("                            </div>      \r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    \r\n");
      out.write("                        <!-- Left and right controls -->\r\n");
      out.write("                        <a class=\"left carousel-control\" href=\"#MyCarousel\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("                          <span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("                          <span class=\"sr-only\">Previous</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a class=\"right carousel-control\" href=\"#MyCarousel\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("                          <span class=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("                          <span class=\"sr-only\">Next</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                \r\n");
      out.write("                    </div>\r\n");
      out.write(" \r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
